roll back to eb2142136bef4e7f58f922bdb3e84bfe1b3a8a07 (3.1.6-14)

diff --git a/clustermgr-cli b/clustermgr-cli
--- a/clustermgr-cli
+++ b/clustermgr-cli
@@ -5,14 +5,31 @@ CELERY_PID="$HOME/.clustermgr/celery.pid"
 CELERY_BEAT_PID="$HOME/.clustermgr/celery-beat.pid"
 GUNICORN_PID="$HOME/.clustermgr/gunicorn.pid"
 PW_FILE="$HOME/.clustermgr/.pw"
-NEW_UUID=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`
+NEW_UUID=`head /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`
 app=`which clusterapp.py`
 
+if ! java -version 2>&1 >/dev/null | grep -q "version"; then
+  echo "Java is not found in PATH. Please install Java and/or add PATH before starting Cluster Manager."
+  exit
+fi
 
 start() { 
     echo "Upgrading Database"
     $app db upgrade
-    
+
+    if [ ! -f "$HOME/.clustermgr/instance" ]
+    then
+        mkdir -p "$HOME/.clustermgr/instance/"
+        
+    fi
+
+    printf "DEBUG = False\nSECRET_KEY = '$NEW_UUID'\nLICENSE_ENFORCEMENT_ENABLED = False" > "$HOME/.clustermgr/instance/config.py"
+
+    if [ ! -f "$HOME/.clustermgr/.start" ]
+    then
+        echo `date +%s` > $HOME/.clustermgr/.start
+    fi
+
     echo "Starting Celery Worker"
     if [ -f "$CELERY_PID" ]
     then
